name: Analyze
description: Analyze next.js bundle size
inputs:
  workflow:
    required: true
    description: Workflow file name
runs:
  using: composite
  steps:
    - name: Analyze bundle
      run: npx -p nextjs-bundle-analysis report
      shell: bash
    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: .next/analyze/__bundle_analysis.json
    - name: Download base branch bundle stats
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow }}
        branch: main
        name: bundle
        path: .next/analyze/base
    - name: Compare with base branch bundle
      run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare
      shell: bash
    - name: Get comment body
      id: get-comment-body
      run: |
        body=$(cat .next/analyze/__bundle_analysis_comment.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo ::set-output name=body::$body
      shell: bash
    - name: Post bundle size comment to commit
      uses: peter-evans/commit-comment@v2
      with:
        body: ${{ steps.get-comment-body.outputs.body }}
