name: Playwright
description: Run playwright test
inputs:
  args:
    required: true
    default: ''
    description: Args passed to "playwright test"
runs:
  using: composite
  steps:
    - name: Prepare playwright
      uses: ./.github/actions/prepare-playwright
    - name: E2E test
      run: yarn e2e ${{ inputs.args }}
      shell: bash
