name: Continuous Integration

on:
  push:
    branches:

jobs:
  onboard:
    uses: ./.github/workflows/onboard.yaml

  setup:
    uses: ./.github/workflows/setup.yaml
    if: ${{ needs.onboard.outputs.should_skip != 'true' }}
    needs:
      - onboard

  lint:
    uses: ./.github/workflows/lint.yaml
    needs:
      - setup

  ut:
    uses: ./.github/workflows/ut.yaml
    needs:
      - setup

  e2e:
    uses: ./.github/workflows/e2e.yaml
    needs:
      - setup

  lighthouse:
    uses: ./.github/workflows/lighthouse.yaml
    needs:
      - setup
      - lint
      - ut
      - e2e

  storybook:
    uses: ./.github/workflows/storybook.yaml
    needs:
      - setup
      - lint
      - ut
      - e2e
