name: Continuous Integration

on:
  push:
    branches-ignore:
      - 'bot/*'

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      workflow: ci.yaml

  lint:
    uses: ./.github/workflows/lint.yaml
    needs:
      - setup

  ut:
    uses: ./.github/workflows/ut.yaml
    needs:
      - setup

  storybook:
    uses: ./.github/workflows/storybook.yaml
    needs:
      - setup
      - lint
      - ut

  setup-e2e:
    uses: ./.github/workflows/setup-e2e.yaml
    needs:
      - setup
      - lint
      - ut

  e2e:
    uses: ./.github/workflows/e2e.yaml
    needs:
      - setup
      - setup-e2e

  lighthouse:
    uses: ./.github/workflows/lighthouse.yaml
    needs:
      - setup
      - setup-e2e
