name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Check if skippable
        uses: fkirc/skip-duplicate-actions@master
        id: skip_check
        with:
          paths_ignore: '[".husky", ".vscode", ".commitlintrc.js", ".editorconfig", ".lintstagedrc", "README.md", "renovate.json"]'

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ci-${{ github.ref }}
    needs:
      - pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Vercel
        id: deploy-to-vercel
        uses: amondnet/vercel-action@v20
        if: "!startsWith(github.ref, 'refs/heads/renovate/')"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') && '--prod' || '' }}
