name: Deploy

on:
  workflow_call:
    inputs:
      production:
        type: boolean
        required: true
        description: Whether to deploy to production environment
    secrets:
      vercel-token:
        required: true
        description: Vercel Token
      vercel-org-id:
        required: true
        description: Vercel Organization ID
      vercel-project-id:
        required: true
        description: Vercel Project ID

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Vercel
        uses: ./.github/actions/deploy
        with:
          production: ${{ inputs.production }}
          github-token: ${{ secrets.github-token }}
          vercel-token: ${{ secrets.vercel-token }}
          vercel-org-id: ${{ secrets.vercel-org-id }}
          vercel-project-id: ${{ secrets.vercel-project-id }}
