name: E2E Test

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: E2E test
        run: yarn e2e
