name: E2E Test

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: E2E test
        uses: ./.github/actions/playwright
        with:
          tag: '@vrt'
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: test-results
