name: E2E Test

on:
  workflow_call:
    inputs:
      args:
        required: true
        type: string
        description: Args for PlayWright

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chromium
          - chromium mobile
          - firefox
          - webkit
          - webkit tablet
          - webkit mobile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: Prepare E2E test
        uses: ./.github/actions/prepare-playwright
      - name: E2E test
        uses: ./.github/actions/playwright
        with:
          args: ${{ inputs.args }} --project '${{ matrix.browser }}'
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.browser }}
          path: test-results
