name: Lighthouse

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: Prepare E2E test
        uses: ./.github/actions/prepare-playwright
      - name: E2E test
        uses: ./.github/actions/playwright
        with:
          args: e2e/tests/lighthouse.spec.ts --project chromium
