name: Onboard

on:
  workflow_call:
    outputs:
      should_skip:
        description: Whether to skip following jobs
        value: ${{ jobs.onboard.outputs.should_skip }}

jobs:
  onboard:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Check if skippable
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
          concurrent_skipping: same_content_newer
          paths_ignore: '[".husky", ".vscode", ".commitlintrc.js", ".editorconfig", ".lintstagedrc", "README.md", "renovate.json"]'
