name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  onboard:
    uses: ./.github/workflows/onboard.yaml

  setup:
    uses: ./.github/workflows/setup.yaml
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs:
      - onboard

  lint:
    uses: ./.github/workflows/lint.yaml
    needs:
      - setup

  ut:
    uses: ./.github/workflows/ut.yaml
    needs:
      - setup

  # e2e:
  #   uses: ./.github/workflows/e2e.yaml
  #   needs:
  #     - setup

  lighthouse:
    uses: ./.github/workflows/lighthouse.yaml
    needs:
      - setup
      - lint
      - ut
      # - e2e

  storybook:
    uses: ./.github/workflows/storybook.yaml
    needs:
      - setup
      - lint
      - ut
      # - e2e

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - setup
      - lint
      - ut
      # - e2e
    with:
      production: false
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
