name: Setup

on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
        description: Workflow file name

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: Analyze
        uses: ./.github/actions/analyze
        with:
          workflow: ${{ inputs.workflow }}
