name: Update Snapshots

on:
  issue_comment:
    types:
      - created

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '📸' }}
    steps:
      - name: Add a rocket reaction to the comment
        run: |
          curl \
            -X POST \
            -u ${{ secrets.BOT_NAME }}:${{ secrets.BOT_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            ${{ github.event.comment.url }}/reactions \
            -d '{"content":"rocket"}'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR head
        run: |
          hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: E2E test
        uses: ./.github/actions/playwright
        with:
          args: '--update-snapshots'
      - name: Get PR target branch
        id: get-target-branch
        run: echo "::set-output name=name::$(git rev-parse --abbrev-ref HEAD)"
      - name: Commit and push snapshots
        run: |
          git config user.email ${{ secrets.BOT_EMAIL }}
          git config user.name ${{ secrets.BOT_NAME }}
          git checkout -B bot/${{ steps.get-target-branch.outputs.name }} ${{ steps.get-target-branch.outputs.name }}
          git add e2e
          git commit -m 'test: update snapshots'
          git push -u origin HEAD --force-with-lease
      - name: Post a comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :camera_flash: Snapshots Updated :camera_flash:

            See the diff at https://github.com/mizozobu/gotobyu.com/compare/${{ steps.get-target-branch.outputs.name }}...bot/${{ steps.get-target-branch.outputs.name }} and manually merge changes.
      - name: Add a tada reaction to the comment
        run: |
          curl \
            -X POST \
            -u ${{ secrets.BOT_NAME }}:${{ secrets.BOT_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            ${{ github.event.comment.url }}/reactions \
            -d '{"content":"tada"}'
