name: Update Snapshots

on:
  issue_comment:
    types:
      - created

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '📸')}}
    steps:
      - name: Add a rocket reaction to the comment
        run: |
          curl \
            -X POST \
            -u ${{ secrets.BOT_NAME }}:${{ secrets.BOT_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            ${{ github.event.comment.url }}/reactions \
            -d '{"content":"rocket"}'
      - name: Get args for E2E test
        id: get-e2e-args
        uses: actions/github-script@v7
        env:
          COMMENT: ${{ github.event.comment.body }}
        with:
          result-encoding: string
          script: |
            const comment = process.env.COMMENT;
            const result = comment.match(
              /📸\s+```[a-z]*(?:\r\n|\r|\n)([\s\S]*?)(?:\r\n|\r|\n)```/,
            );
            core.setOutput('args', (result?.[1] ?? '').trim());
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR head
        run: |
          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: ./.github/actions/build
      - name: Prepare E2E test
        uses: ./.github/actions/prepare-playwright
      - name: E2E test
        uses: ./.github/actions/playwright
        with:
          args: e2e/tests/visual-regression.spec.ts --update-snapshots ${{ steps.get-e2e-args.outputs.args }}
      - name: Get PR target branch
        id: get-target-branch
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      - name: Commit and push snapshots
        run: |
          git config user.email ${{ secrets.BOT_EMAIL }}
          git config user.name ${{ secrets.BOT_NAME }}
          git push --delete origin bot/${{ steps.get-target-branch.outputs.branch }} || true
          git checkout -B bot/${{ steps.get-target-branch.outputs.branch }} ${{ steps.get-target-branch.outputs.branch }}
          git add e2e
          git commit -m 'test: update snapshots'
          git push -u origin HEAD
      - name: Post a success comment to PR
        if: ${{ success() }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :white_check_mark: Snapshots updated

            See the diff at https://github.com/mizozobu/gotobyu.com/compare/${{ steps.get-target-branch.outputs.branch }}...bot/${{ steps.get-target-branch.outputs.branch }} and manually merge changes.
      - name: Post a failure comment to PR
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :warning: Snapshot update failed

            See the workflow details at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
