name: Unit Test

on:
  workflow_call:

jobs:
  ut:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Unit test
        run: yarn ut
